# Generated by Django 3.0.5 on 2020-05-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabservice',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaintservice',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomservice',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
